spring.application.name=ForGuide

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/forguide}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# MyBatis
mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration